
package pl.bank.bsr;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "BankServiceException", targetNamespace = "http://bsr.bank.pl")
public class BankException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private FaultBean faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public BankException(String message, FaultBean faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public BankException(String message, FaultBean faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: pl.bank.bsr.FaultBean
     */
    public FaultBean getFaultInfo() {
        return faultInfo;
    }

}
